apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-api
  labels:
    app: articles-api
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: articles-api
  template:
    metadata:
      labels:
        app: articles-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - articles-api
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: articles-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGO_URI
              value: {{ .Values.mongo.uri | quote }}
            - name: MONGO_DB_NAME
              value: {{ .Values.mongo.dbName | quote }}
            - name: OTEL_EXPORTER_ENDPOINT
              value: {{ .Values.otel.exporterEndpoint | quote }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.serviceName | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
