apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: articles-api
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: articles-api
                port:
                  number: {{ .Values.service.port }}
