apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jetstream-devops-assignment
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/divyamraj18/jetstream-devops-assignment.git
      targetRevision: master
      path: charts/backend
    - repoURL: https://github.com/divyamraj18/jetstream-devops-assignment.git
      targetRevision: master
      path: charts/mongodb

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
